import React from "react";
import './Modal.css'

import one from '../images/1.png'
import two from '../images/2.png'
import three from '../images/3.png'
import threeEdit from '../images/3edit.png'
import four from '../images/4.png'
import five from '../images/5.png'
import six from '../images/6.png'
import seven from '../images/7.png'
import eight from '../images/8.png'
import nine from '../images/9.png'
import ten from '../images/10.png'
import eleven from '../images/11.png'
import twelve from '../images/12.png'
import thirteen from '../images/13.png'
import fourteen from '../images/14.png'
import fifteen from '../images/15.png'
import sixteen from '../images/16.png'
import seventeen from '../images/17.png'
import eighteen from '../images/18.png'
import nineteen from '../images/19.png'
import twenty from '../images/20.png'
import twentyone from '../images/21.png'
import twentytwo from '../images/22.png'
import twentythree from '../images/23.png'
import twentyfour from '../images/24.png'
import twentyfive from '../images/25.png'
import twentysix from '../images/26.png'
import twentyseven from '../images/27.png'
import twentyeight from '../images/28.png'
import twentynine from '../images/29.png'
import thirty from '../images/30.png'
import thirtyone from '../images/31.png'
import thirtytwo from '../images/32.png'
import thirtythree from '../images/33.png'
import thirtyfour from '../images/34.png'
import thirtyfive from '../images/35.png'
import thirtysix from '../images/36.png'
import thirtyseven from '../images/37.png'
import thirtyeight from '../images/38.png'
import thirtynine from '../images/39.png'
import forty from '../images/40.png'
import fortyone from '../images/41.png'
import fortytwo from '../images/42.png'
import fortythree from '../images/43.png'
import fortyfour from '../images/44.png'
import fortyfive from '../images/45.png'
import fortysix from '../images/46.png'
import fortyseven from '../images/47.png'
import fortyeight from '../images/48.png'
import fortynine from '../images/49.png'
import fifty from '../images/50.png'
import fiftyone from '../images/51.png'
import fiftytwo from '../images/52.png'
import fiftythree from '../images/53.png'
import fiftyfour from '../images/54.png'
import fiftyfive from '../images/55.png'
import fiftysix from '../images/56.png'
import fiftyseven from '../images/57.png'
import fiftyeight from '../images/58.png'
import fiftynine from '../images/59.png'
import sixty from '../images/60.png'
import sixtyone from '../images/61.png'
import sixtytwo from '../images/62.png'
import sixtythree from '../images/63.png'
import sixtyfour from '../images/64.png'
import sixtyfive from '../images/65.png'
import sixtysix from '../images/66.png'
import sixtyseven from '../images/67.png'
import sixtyeight from '../images/68.png'
import sixtynine from '../images/69.png'
import seventy from '../images/70.png'
import seventyone from '../images/71.png'
import seventytwo from '../images/72.png'
import seventythree from '../images/73.png'
import seventyfour from '../images/74.png'
import seventyfive from '../images/75.png'
import seventysix from '../images/76.png'
import seventyseven from '../images/77.png'
import seventyeight from '../images/78.png'
import seventynine from '../images/79.png'
import eighty from '../images/80.png'
import eightyone from '../images/81.png'
import eightytwo from '../images/82.png'
import eightythree from '../images/83.png'
import eightyfour from '../images/84.png'
import eightyfive from '../images/85.png'
import eightysix from '../images/86.png'
import eightyseven from '../images/87.png'
import eightyeight from '../images/88.png'

function Modal(props) {

    function handleImageClick() {
        props.setShowModal(false)
    }
    return (
        <div className="modal" onClick={() => handleImageClick()}>
        <div className="modal-content">
            <img className="modalImg" src={props.imageSrc} alt={props.imageAlt} onClick={() => handleImageClick()}/>
        </div>
        </div>
    );
}

export default Modal;
